### ISSUE TITLE
num_layers argument of the Transformer module

### ISSUE THREAD

**Issue by yyuncong** [maruya24/pytorch_robotics_transformer#3]
Hi! Thank you for the tremendous efforts of open-sourcing this pytorch version! I notice that you use regular list to store each layer instead of nn.ModuleList in the Transformer module and this may cause issues. What I found is that when I increase the num_layers argument, the number of trainable parameters in the model does not increase (fixed after using ModuleList)

This is by far the best pytorch implementation I found because it seems align the original tensorflow version well. I am wondering if you did any sanity checks (other than the provided one) to compare the pytorch version and the original version? Thank you again for the great work!

**Comment by maruya24** [comment]
Thank you for your notice. I was surprised that you had read my codes in detail. I modified the part of the codes that you mentioned. I'm glad that your advice made my codes better.

I'm afraid that I didn't do any sanity checks except for my unittest codes. The reason I didn't do it is that I didn't have enough data.

Thank you for your kind and encouraging words. You made my day.
